#!/bin/bash
apt-get update
apt-get install -y nginx
sed -i 's/listen 80 default_server;/listen 80 default_server;\n    listen [::]:80 default_server;/' /etc/nginx/sites-available/default
service nginx restart
ufw allow 80/tcp
